/**
 * Синхронизация портфолио с Pinterest.
 * Запуск: `npm run sync-pinterest`
 *
 * Что делает:
 * 1. Читает TELEGRAM_… и PINTEREST_… из .env.local
 * 2. Тянет все пины пользователя (или из конкретной доски, если задан PINTEREST_BOARD_ID)
 * 3. Скачивает изображения в public/pinterest/
 * 4. Перезаписывает app/data/photos.ts новым манифестом
 *
 * После выполнения /portfolio и Featured-блок главной автоматически покажут новые фото.
 */
import "dotenv/config";
import { config as dotenv } from "dotenv";
import {
  existsSync,
  mkdirSync,
  readdirSync,
  unlinkSync,
  writeFileSync,
} from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  bestImage,
  listAllPins,
  listBoards,
  PinterestError,
} from "../app/lib/pinterest";

const here = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(here, "..");
dotenv({ path: join(projectRoot, ".env.local") });

const token = process.env.PINTEREST_ACCESS_TOKEN;
const boardId = process.env.PINTEREST_BOARD_ID || undefined;

if (!token) {
  console.error("❌ PINTEREST_ACCESS_TOKEN не задан в .env.local.");
  console.error(
    "   См. SETUP.md, секция «Pinterest» — как получить токен на developers.pinterest.com.",
  );
  process.exit(1);
}

const outDir = join(projectRoot, "public", "pinterest");
const manifestFile = join(projectRoot, "app", "data", "photos.ts");

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true });
if (!existsSync(dirname(manifestFile)))
  mkdirSync(dirname(manifestFile), { recursive: true });

console.log("🧷 sync-pinterest");
console.log(`   board: ${boardId ?? "(все пины пользователя)"}`);
console.log(`   output: ${outDir}\n`);

// Проверим доступы, заодно покажем доступные доски
try {
  const boards = await listBoards(token);
  console.log(`   Найдено досок: ${boards.length}`);
  if (boards.length > 0) {
    boards.slice(0, 10).forEach((b) =>
      console.log(`     · ${b.name} — ${b.pin_count} пинов  (id: ${b.id})`),
    );
    if (boards.length > 10) {
      console.log(`     ... и ещё ${boards.length - 10}`);
    }
    if (!boardId) {
      console.log(
        "\n   Совет: укажи PINTEREST_BOARD_ID в .env.local чтобы тянуть только из одной доски.",
      );
    }
  }
} catch (err) {
  if (err instanceof PinterestError) {
    console.error(
      `❌ Pinterest API ответил ${err.status}. Проверь токен и scope (нужно boards:read,pins:read).`,
    );
    console.error(JSON.stringify(err.body, null, 2));
    process.exit(1);
  }
  throw err;
}

console.log("\n📥 Получаю пины…");
const pins = await listAllPins(token, { boardId });
console.log(`   Получено: ${pins.length}\n`);

if (pins.length === 0) {
  console.log("⚠️  Пинов не нашлось. Проверь токен/доску и попробуй снова.");
  process.exit(0);
}

// Чистим старые скачанные изображения, чтобы не копились удалённые
for (const f of readdirSync(outDir)) {
  if (/\.(jpe?g|png|webp)$/i.test(f)) {
    unlinkSync(join(outDir, f));
  }
}

const manifest: Array<{ src: string; w: number; h: number; title?: string }> =
  [];

let success = 0;
let failed = 0;

for (let i = 0; i < pins.length; i++) {
  const pin = pins[i];
  const img = bestImage(pin);
  if (!img) {
    failed++;
    continue;
  }
  const filename = `${pin.id}.jpg`;
  const filePath = join(outDir, filename);

  process.stdout.write(`\r   [${i + 1}/${pins.length}] ${filename} …`);

  try {
    const r = await fetch(img.url);
    if (!r.ok) throw new Error(`HTTP ${r.status}`);
    const buf = Buffer.from(await r.arrayBuffer());
    await writeFile(filePath, buf);
    manifest.push({
      src: `/pinterest/${filename}`,
      w: img.width,
      h: img.height,
      title: pin.title || pin.alt_text || undefined,
    });
    success++;
  } catch (err) {
    failed++;
    console.warn(
      `\n   ⚠️  ${filename}: ${err instanceof Error ? err.message : err}`,
    );
  }
}
process.stdout.write("\n");

// Пишем манифест в TS-файл
const ts = `// Auto-generated by scripts/sync-pinterest.mts — do not edit by hand.
// Synced ${new Date().toISOString()} · ${manifest.length} pins
export type Photo = { src: string; w: number; h: number; title?: string };

export const photos: Photo[] = ${JSON.stringify(manifest, null, 2)};
`;

writeFileSync(manifestFile, ts);

console.log(`\n✅ Готово. ${success} скачано, ${failed} с ошибкой.`);
console.log(`   Манифест: ${manifestFile}`);
console.log(
  "   Перезапусти dev-сервер (или просто обнови /portfolio) — увидишь новые фото.",
);
